### ISSUE TITLE
incompatible with idea 2020.1

### ISSUE THREAD

**Issue by ehlxr** [Unthrottled/themed-components#1]
incompatible with idea 2020.1

**Comment by Unthrottled** [comment]
Hey! I fixed the issue, [on this release](https://github.com/Unthrottled/themed-components/releases/tag/v1.1.0).

I can publish this to the marketplace so you can get automatic updates (if you want).

[You can also set up my custom plugin repository as well, so you can get automatic updates as well.](https://github.com/Unthrottled/jetbrains-plugin-repository#jetbrains-custom-repository)
