### ISSUE TITLE
Title Bar color Customization

### ISSUE THREAD

**Issue by Unthrottled** [Unthrottled/themed-components#10]
As a user, I would like the ability to customize the focused/inactive foreground color of the title bar, so that I can make it a color that I can read.

Relevant issue
https://github.com/one-dark/jetbrains-one-dark-theme/issues/203#issuecomment-752418408

**Comment by Unthrottled** [comment]
@yxd0018 :point_up: once this feature is implemented, then you'll be able to customize the title bar foreground color. :slightly_smiling_face:

**Comment by yxd0018** [comment]
will this work for win 10?

**Comment by Unthrottled** [comment]
Yes, that is the idea. It should work for both Windows 10 and MacOS, anything that supports the `TitlePane.infoForeground` theme property.

**Comment by Unthrottled** [comment]
@yxd0018 The latest version of [Themed Components](https://plugins.jetbrains.com/plugin/14322-themed-components/versions/stable/111538), with the title foreground change feature, now is available.
